apiVersion: v1
kind: Namespace
metadata:
  name: "kubernetes-cluster-nikhilsharma03"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "app-settings-master"
  namespace: "kubernetes-cluster-nikhilsharma03"
  labels:
    app: "app-settings-master"
data:
  API_URL: "http://www.facebook.com"
  Environment: "Production"
  Language: "Hindi"
---
apiVersion: v1
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
kind: Secret
metadata:
  name: nagp-secret
  namespace: kubernetes-cluster-nikhilsharma03
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagp-prod-kubernetes
  namespace: kubernetes-cluster-nikhilsharma03
  labels:
    app: nagp-production
spec:
  template:
    metadata:
      name: nagp-development-pod
      labels:
        app: nagp-production
        type: front-end
    spec:
      containers:
        - name: nagp-prod-containers
          image: nikneal91/i-nikhilsharma03-master
          envFrom:
            - configMapRef:
                name: "app-settings-master"
            - secretRef:
                name: "nagp-secret"

  replicas: 4
  selector:
    matchLabels:
      type: front-end
      app: nagp-production

---

apiVersion: v1
kind: Service
metadata:
  name: nagp-prod-lb-service
  namespace: "kubernetes-cluster-nikhilsharma03"
spec:
  type: LoadBalancer
  selector:
    app: nagp-production
  ports:
    - targetPort: 8080
      port: 8090
      nodePort: 30085
