apiVersion: v1
kind: Namespace
metadata:
  name: "kubernetes-cluster-nikhilsharma03"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "app-settings"
  namespace: "kubernetes-cluster-nikhilsharma03"
  labels:
    app: "app-settings"
data:
  API_URL: "http://www.google.com"
  Environment: "development"
  Language: "English"
---
apiVersion: v1
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
kind: Secret
metadata:
  name: nagp-secret
  namespace: kubernetes-cluster-nikhilsharma03
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagp-demo-kubernetes
  namespace: kubernetes-cluster-nikhilsharma03
  labels:
    app: nagp-development
spec:
  template:
    metadata:
      name: nagp-development-pod
      labels:
        app: nagp-development
        type: front-end
    spec:
      containers:
        - name: nagp-demo-containers
          image: nikneal91/i-nikhilsharma03-develop
          envFrom:
            - configMapRef:
                name: app-settings
            - secretef:
                name: "nagp-secret"

  replicas: 4
  selector:
    matchLabels:
      type: front-end
      app: nagp-development

---

apiVersion: v1
kind: Service
metadata:
  name: nagp-demo-lb-service
  namespace: "kubernetes-cluster-nikhilsharma03"
spec:
  type: LoadBalancer
  selector:
    app: nagp-development
  ports:
    - targetPort: 8080
      port: 80
      nodePort: 30081
